target 'CWEyeFiServer', :exclusive => true do
  pod "CWEyeFiServer", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "CWEyeFiServer", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  pod 'CocoaHTTPServer', '~> 2.3'
  pod 'Brett', '~> 1.0'
end
